apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ayn0xg8nh-java-quarkus 
  janus-idp.io/tekton: ayn0xg8nh-java-quarkus
  backstage.io/kubernetes-id: ayn0xg8nh-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ayn0xg8nh-java-quarkus
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml